workflows:
  flutter:
    name: Flutter Build Workflow
    instance_type: mac_mini
    # Removed extra fields like 'description' and 'platforms'
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build APK
        script: |
          flutter build apk --release
